spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 05570537474036e77c30e6f559ebe2a5
  mail:
    password: tzkh kjjb plww orvt
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname